[build]
  publish = "public"
  functions = "netlify/functions"
  command = "npm install"

[[redirects]]
  from = "/salon/*"
  to = "/salon/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
